### ISSUE TITLE
please make this work for new versions amd 64 bit

### ISSUE THREAD

**Issue by ZachsToysandFamily** [khang06/dominohook#4] opened 2024-09-02 01:20 UTC
i got this now and its pretty good, but it doesent work for domino 1.44 x32 and domino 1.45 beta x64 so please make it work for those!

**Comment by khang06** [comment] 2024-09-02 02:45
duplicate of #3

**Closed as not planned by khang06** 2024-09-02 02:45 UTC

**Comment by ZachsToysandFamily** [comment] 2024-09-02 03:32
> duplicate of #3

i didnt see that issue before writing mine
